### ISSUE TITLE
Small bug in “Breakpoints” demo

### ISSUE THREAD

**Issue by simevidas** [filamentgroup/snapper#18] opened 2016-06-16 06:28 UTC
URL: http://filamentgroup.github.io/snapper/demo/breakpoints.html

In Firefox and Edge (on Windows 10), there is a slight overflow on the right edge. This causes the Next button to scroll the images only a few pixels, every other time. This issue also appears on iPhone 6 in landscape mode.

![capture](https://cloud.githubusercontent.com/assets/716405/16107319/f9bd51e0-339b-11e6-8e65-f7ab8af444d5.PNG)

**Comment by scottjehl** [comment] 2017-06-29 03:15
Late on the reply here but I can't reproduce this in latest so I'm closing as fixed. We've done some rounding error fixes this year that are likely related to making this work better now. If you still see it though, let us know and I'll look again. thanks!

**Closed by scottjehl** 2017-06-29 03:15 UTC
